title: Udoy Das
url: "https://udoydas.net"
baseurl: "/"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

# footer: yes
# footer_url: "https://github.com/ankitsultana"
# footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/"
 - name: "Education"
   link: "education"
 - name: "Publication"
   link: "publication"
 - name: "Projects"
   link: "projects"
 - name: "Skills"
   link: "skills"
 - name: "Contact"
   link: "contact"
